### ISSUE TITLE
Chapter 2 - From Data Model to Concept Model?

### ISSUE THREAD

**Issue by ChuckNoelke** [KGConf/BookClub-OntologyEngineering#5]
Question to Chapter 2.4 BUSINESS VOCABULARY DEVELOPMENT

In an enterprise a knowledge graph project often uses relational data from existing applications.
So, there is already a detailed data model available with the schema. 

What is the best way to transfer that data model into a concept model representing real things, propeties and logic?

Thanks,
Marcus

**Comment by msesboue** [comment]
answered at the end of the second session
