### ISSUE TITLE
Ch 2 Section 2.5 Evaluating Ontologies: Correctness

### ISSUE THREAD

**Issue by lrumanes** [KGConf/BookClub-OntologyEngineering#7]
How can ontologies be evaluated for correctness of content, and not just for logical consistency and coherence?  Is this all done during authoring or are there approaches for doing it retrospectively?

**Comment by msesboue** [comment]
This question has been indirectly answered during the second session and a lot of links are available in the [chapter 2 wiki page](https://github.com/KGConf/BookClub-OntologyEngineering/wiki/Chapter-2:-Before-you-begin)
