### ISSUE TITLE
Natural language grammar to concept map

### ISSUE THREAD

**Issue by dvaranka** [KGConf/BookClub-OntologyEngineering#8]
Hello
I am interested to know if techniques exist for the transformation of English grammar diagrams, such as Phrase Bracketing converted to concept maps.  I understand concept mapping but I can't find a source that explains diagramming conventions used by linguists to be able to relate the two approaches. 
thanks

**Comment by msesboue** [comment]
Not sure if it helps, but those ontologies might be of some help:
* https://www.w3.org/2016/05/ontolex/
* https://lemon-model.net/index.php
